apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ include "etimo-slack-scraper.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "etimo-slack-scraper.name" . }}
    helm.sh/chart: {{ include "etimo-slack-scraper.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 300
  schedule:
    # min hour dom mon dow
    " 30  */2  *   *   *"
  jobTemplate:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "etimo-slack-scraper.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      template:
        metadata:
          labels:
            app.kubernetes.io/name: {{ include "etimo-slack-scraper.name" . }}
            app.kubernetes.io/instance: {{ .Release.Name }}
        spec:
          initContainers:
          - name: blog-puller
            image: alpine
            # TODO: Build a real image instead of this monstrosity,
            # or merge into the main image
            args:
            - "sh"
            - "-c"
            - "apk add git openssh-client && git clone git@github.com:etimo/etimo.github.io.git /blog --depth=1 && chmod a+rwX -R /blog"
            volumeMounts:
            - name: blog
              mountPath: /blog
            - name: ssh-keys
              mountPath: /root/.ssh
          - name: chat-puller
            image: {{ .Values.images.etimo_slack_static_blogger | quote }}
            args:
            - "-c"
            - "/config/slackscraper.json"
            volumeMounts:
            - name: blog
              mountPath: /blog
            - name: config
              mountPath: /config
          containers:
          - name: blog-pusher
            image: alpine
            # TODO: Build a real image instead of this monstrosity,
            # or merge into the main image
            args:
            - "sh"
            - "-c"
            - "apk add git openssh-client && cd /blog && git add . && git config user.email 'etimo@etimo.se' && git config user.name 'Etimo AB' && git commit -m 'Auto scrape update' || true && git push || true"
            volumeMounts:
            - name: blog
              mountPath: /blog
            - name: ssh-keys
              mountPath: /root/.ssh
          volumes:
          - name: blog
            emptyDir: {}
          - name: config
            secret:
              secretName: {{ include "etimo-slack-scraper.fullname" . }}-config
          - name: ssh-keys
            secret:
              secretName: {{ include "etimo-slack-scraper.fullname" . }}-ssh-keys
              defaultMode: 0600
          restartPolicy: Never
