apiVersion: v1
kind: Secret
metadata:
  name: {{ include "etimo-slack-scraper.fullname" . }}-ssh-keys
type: Opaque
data:
  id_ed25519: {{ .Values.sshKeys.private | b64enc | quote }}
  "id_ed25519.pub": {{ .Values.sshKeys.public | b64enc | quote }}
  known_hosts: {{ .Values.sshKeys.knownHosts | b64enc | quote }}
