language: scala
jdk:
- openjdk8
dist: xenial
before_install:
- curl https://nixos.org/nix/install | sh
- source /home/travis/.nix-profile/etc/profile.d/nix.sh
- nix-channel --update
- nix-env -iA nixpkgs.kubectl nixpkgs.kubernetes-helm nixpkgs.git-crypt
- openssl aes-256-cbc -K $encrypted_1bba31cae831_key -iv $encrypted_1bba31cae831_iv -in deploy/git-crypt.key.enc -out deploy/git-crypt.key -d
- git crypt unlock deploy/git-crypt.key
deploy:
  provider: script
  script: bash deploy.sh
  on:
    branch: master
